### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by ece-mohammad** [ece-mohammad/B.O.G-basic-name-search-tool#9]
Search the following Twitter handles

- https://twitter.com/GazaMartyrs?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
- https://twitter.com/Gaza_Shaheed

**Comment by smashah** [comment]
https://github.com/d60/twikit

**Comment by ece-mohammad** [comment]
@smashah Great find! That should help with twitter.
It's a Python package though, I thought the tool should be in JS?

**Comment by smashah** [comment]
@ece-mohammad lets get the job done as quick as possible with whatever tools we have then we can consolidate later. this is a good tool for now because you're good at python
